# Sample .travis.yml for R projects

language: r
warnings_are_errors: false
sudo: required

r_packages:
 - dplyr
 - ggplot2
 - magrittr
 - rvest
r_github_packages:
 - dichika/yeah
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  slack: us-lab:xTJ3Yh37JO4luAh9Yx6gXTck
  email: false
